SettingGroup:
    Society : 'Configuration de la Société'
    SocietyTargets: 'Objectifs'
    PrintableDocs : "Configuration de l'impression des documents"
    EmailsConfig : 'Configuration des addresses Emails'
    EmailsTexts : 'Configuration des textes d''Emails'
    HUB-Hotel : 'Configuration du HUB Hôtel'
    HUB-Transfer : 'Configuration du HUB Transfert'
    HUB-Flight : 'Configuration du HUB Vol'
    System : 'Configuration Système'
    B2CSocialNetworks : 'Réseaux Sociaux (B2C)'
    StaticPages : 'Pages Statiques'
    DocumentContentHotel : 'Contenu personnalisé : Module Hôtel'
    DumboSystemCheck : 'Vérification du système Dumbo.'



SocietyTargets:
    OrderNumber: 'Nombre de commandes par jour'
    OrderLineNumber: 'Nombre de réservations par jour'
    CustomerNumber: 'Nombre de clients par jour'

Society:
    name : 'Raison Social'
    MF: 'Matricule fiscale'
    RC: 'Registre de commerce'
    Address: 'Adresse'
    Phone: 'Téléphone'
    Whatsapp: 'Whatsapp'
    Fax: 'Fax'
    RIB : 'RIB'
    EmailContact: 'Email Société'
    Hotline: 'Hotline'
    Description: 'Description'

Currency:
    Currency1 : "Devise 1"
    Currency2 : "Devise 2"
    Currency3 : "Devise 3"
    Currency4 : "Devise 4"
    Currency5 : "Devise 5"
    Currency6 : "Devise 6"
    Currency7 : "Devise 7"
    Currency8 : "Devise 8"
    Currency9 : "Devise 9"

StaticPages:
    LegalNotice: 'Mentions légales'
    PracticalInformation: 'Information Pratique'
    PurchaseCondition: 'Conditions de vente'
    ProtocolsConfidentiality: 'Politique & confidentialité'
    RecruitingAgency: 'Agence Recrute'

PrintableDocs:
    Logo: 'Logo'
    Signature: 'Cachet'
    BackgroundColor: 'Couleur de fond d''impression'
    LogoHeight: 'Hauteur Logo'
    LogoWidth: 'Largeur Logo'
    StampHeight: 'Hauteur Cachet'
    StampWidth: 'Largeur Cachet'
    FooterHeight: 'Hauteur Pied de page'

EmailsConfig:
    EmailFrom_Booking : 'Email de (Réservations)'
    EmailFrom_Contact : 'Email de (Contact)'
    EmailFrom_Account : 'Email de (Comptes)'
    EmailDisplay_B2C : 'Email à afficher aux B2C'
    EmailDisplay_B2B : 'Email à afficher aux B2B'
    Email_CC: 'Email Copie (CC)'

B2CSocialNetworks:
    Facebook: 'Facebook'
    LinkedIn: 'Linked IN'
    Instagram: 'Instagram'
    Twitter: 'Twitter'

HUB-Hotel:
    ApiKey: 'Clé API HÔTEL'
    Url : 'URL DU HUB HÔTEL'

HUB-Transfer:
    ApiKey: 'Clé API DU HUB TRANSFERT'
    Url: 'URL DU HUB TRANSFERT'


HUB-Flight:
    ApiKey: 'Clé API DU HUB VOL'
    Url: 'URL DU HUB VOL'


System:
    Currency: 'Devise'
    ModuleHotelContract: 'Activation Contrats Hôtels (1: oui)'
    ModuleHotel: 'Activation Module Hotel (1: oui)'
    ModuleTransfer: 'Activation Module Transfert (1: oui)'
    ModuleFlight: 'Activation Module Vol (1: oui)'
    ModuleCustomService: 'Service Libre Activation (1: yes)'
    IsB2B: 'Mode B2B (1: oui)'
    MidOfficeUrl: 'URL du Mid-Office'

DocumentContentHotel:
    VoucherInfosFR : "Voucher Hotel: Infos (FR)"
    VoucherInfosEN : "Voucher Hotel: Infos (EN)"